### ISSUE TITLE
undefined is not an object(evaluating 'ReactNativeFingerprintScensor.isSensorAvailable')

### ISSUE THREAD

**Issue by antbaobao** [hieuvp/react-native-fingerprint-scanner#52] opened 2018-08-01 15:53 UTC

**Comment by phillbaker** [comment] 2018-09-09 21:10
Hi @antbaobao thanks for opening an issue.  I've recently been added as a collaborator on this repo and am getting familiar with the open issues.

Can you provide a complete example demonstrating how to reproduce this error?

Looking at the [README documentation for this method](https://github.com/hieuvp/react-native-fingerprint-scanner#issensoravailable-android-ios), it looks like the general way to call this function is `FingerprintScanner.isSensorAvailable()`, however, if you've imported the library differently then what you posted may work.

**Comment by phillbaker** [comment] 2018-09-15 23:59
Closing for now as there's been no follow up. @antbaobao please re-open if there are more details!

**Closed by phillbaker** 2018-09-15 23:59 UTC
