### ISSUE TITLE
react-native 0.60 android x migration

### ISSUE THREAD

**Issue by Thomazella** [hieuvp/react-native-fingerprint-scanner#89] opened 2019-07-03 23:48 UTC
I'm using version 2.6.0 of the libraty because it seems to have the android native lib updated to a version that supports androidX, but I still run into a build error (also happens on 2.6.1):

```
/Users/vamac/Desktop/60scaMo/node_modules/react-native-fingerprint-scanner/android/src/main/java/com/hieuvp/fingerprint/ReactNativeFingerprintScannerModule.java:11: error: cannot find symbol
import com.wei.android.lib.fingerprintidentify.base.BaseFingerprint.FingerprintIdentifyExceptionListener;
                                                                   ^
  symbol:   class FingerprintIdentifyExceptionListener
  location: class BaseFingerprint
/Users/vamac/Desktop/60scaMo/node_modules/react-native-fingerprint-scanner/android/src/main/java/com/hieuvp/fingerprint/ReactNativeFingerprintScannerModule.java:12: error: cannot find symbol
import com.wei.android.lib.fingerprintidentify.base.BaseFingerprint.FingerprintIdentifyListener;
                                                                   ^
  symbol:   class FingerprintIdentifyListener
  location: class BaseFingerprint
/Users/vamac/Desktop/60scaMo/node_modules/react-native-fingerprint-scanner/android/src/main/java/com/hieuvp/fingerprint/ReactNativeFingerprintScannerModule.java:51: error: cannot find symbol
                new FingerprintIdentifyExceptionListener() {
                    ^
  symbol:   class FingerprintIdentifyExceptionListener
  location: class ReactNativeFingerprintScannerModule
/Users/vamac/Desktop/60scaMo/node_modules/react-native-fingerprint-scanner/android/src/main/java/com/hieuvp/fingerprint/ReactNativeFingerprintScannerModule.java:82: error: cannot find symbol
        getFingerprintIdentify().startIdentify(MAX_AVAILABLE_TIMES, new FingerprintIdentifyListener() {
                                                                        ^
  symbol:   class FingerprintIdentifyListener
  location: class ReactNativeFingerprintScannerModule
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fingerprint-scanner:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
```

i'm updating to 0.60, using jetifier. Help or guidance is much appreciated 🙏

**Comment by phillbaker** [comment] 2019-07-04 00:31
Dupe of #88?

**Comment by Thomazella** [comment] 2019-07-04 02:20
@phillbaker yeah it's very related. Error message is different tho so I opened a new issue. I'm not an android dev so it may as well be the same thing underneath

**Comment by phillbaker** [comment] 2019-07-04 21:31
@Thomazella can you include the output of `react-native info`?

**Comment by phillbaker** [comment] 2019-07-07 20:23
Going to consolidate this into #88 - we'll support androidx on react native 0.60+ only.

**Closed by phillbaker** 2019-07-07 20:23 UTC
