### ISSUE TITLE
Detect if device add/remove a fingerprint/touchid

### ISSUE THREAD

**Issue by llduchuy91** [hieuvp/react-native-fingerprint-scanner#87] opened 2019-06-12 08:49 UTC
Can you provide a method to detect if user has add/remove a fingerprint/touchid from list saved ?

**Comment by phillbaker** [comment] 2019-06-26 17:00
I don't understand the question/ask, can you give an example?

Is this potentially a duplicate of https://github.com/hieuvp/react-native-fingerprint-scanner/issues/47 or https://github.com/hieuvp/react-native-fingerprint-scanner/issues/66?

**Comment by phillbaker** [comment] 2019-07-07 20:24
Closing as there hasn't been a followup. I believe this is a dupe of #66.

**Closed by phillbaker** 2019-07-07 20:24 UTC
