### ISSUE TITLE
getting "FingerprintScannerError" error on iOS device when i am trying use either FingerprintScanner.authenticate() or isSensorAvailable()

### ISSUE THREAD

**Issue by mahesh-vidhate** [hieuvp/react-native-fingerprint-scanner#59] opened 2018-10-10 20:34 UTC
here is my code, which is exactly same as the given in example project code - 

FingerprintPopup.ios file --

componentDidMount() {
    FingerprintScanner
      .authenticate({ description: 'Scan your fingerprint on the device scanner to continue' })
      .then(() => {
         this.props.handlePopupDismissed(true);
      })
      .catch((error) => {
          console.log(error);
      });
  }

componentWillUnmount() {
    FingerprintScanner.release();
}

render() {
    return false;
 }
}`

inside app.js --

`useTouchId = () =>{
        FingerprintScanner
        .isSensorAvailable()
        .then(biometryType => {
            console.log("***** biometric found --- ", biometryType);
            this.isTouchAvailable = true;
            this.handleFingerprintShowed();
        })
        .catch(error => {
          console.log("****** biometric not found --- ", error);
          this.isTouchAvailable = false;
     }); 
}

handleFingerprintShowed = () => {
        this.setState({ popupShowed: true });
};
    
handleFingerprintDismissed = (result) => {
        result ? this.performAction() : this.setState({ popupShowed: false });
};

componentWillUnmount(){
        console.log("Pin componentWillUnmount");
        FingerprintScanner.release();
}`

I have fingerprints registered in my iOS device, still getting the error while using the above mentioned functions. Please help me here.

Error -> 
FingerprintScannerError {name: "FingerprintScannerNotSupported", stack: "FingerprintScannerNotSupported↵    at _default (bl…8.43.145:8081/debugger-ui/debuggerWorker.js:72:58"}
name: "FingerprintScannerNotSupported"
stack: "FingerprintScannerNotSupported↵    at _default (blob:http://192.168.43.145:8081/0281a052-c6e0-4e0b-a408-228ddf97cbf5:125886:12)↵    at blob:http://192.168.43.145:8081/0281a052-c6e0-4e0b-a408-228ddf97cbf5:125813:50↵    at MessageQueue.__invokeCallback (blob:http://192.168.43.145:8081/0281a052-c6e0-4e0b-a408-228ddf97cbf5:4415:18)↵    at blob:http://192.168.43.145:8081/0281a052-c6e0-4e0b-a408-228ddf97cbf5:4166:18↵    at MessageQueue.__guard (blob:http://192.168.43.145:8081/0281a052-c6e0-4e0b-a408-228ddf97cbf5:4318:13)↵    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://192.168.43.145:8081/0281a052-c6e0-4e0b-a408-228ddf97cbf5:4165:14)↵    at http://192.168.43.145:8081/debugger-ui/debuggerWorker.js:72:58"
__proto__: Wrapper

**Comment by phillbaker** [comment] 2018-10-12 17:22
@mahesh-vidhate sorry to hear you're having issues. This seems similar to https://github.com/hieuvp/react-native-fingerprint-scanner/issues/9.

Can you clarify:
* the version of react native you're using?
* the device type you're testing on?
* the version of this library you're using?

**Comment by nehab05a** [comment] 2018-10-22 08:53
Any update on this?
I am having same issue and after registering faceId/touchId my app crashes on iOS.

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.8.0
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.1 => 16.5.2
  react-native: ^0.55.0 => 0.55.4

I am using "2.2.1" version of react-native-fingerprint-scanner and also tried to update it to "2.5.0" but it still fails to function.

**Comment by phillbaker** [comment] 2018-10-28 22:05
Hi @mahesh-vidhate since there hasn't been any update or clarification, I'm going to close this issue. Please re-open if there are further details that can help reproduce this.

**Closed by phillbaker** 2018-10-28 22:05 UTC

**Comment by mahesh-vidhate** [comment] 2018-10-30 06:01
@phillbaker 
Sorry for the delay. This issue is got fixed now, It was due to 'live reload'. During the testing, when I try to reload the new bundle multiple times using the live reload, maybe, in this case, it fails to detect the fingerprint sensor and this error comes. Also when you try to authenticate fingerprint with the wrong one multiple times, the iOS system disables the fingerprint and this error comes.
So now when I see this error, I just restart the application and also make sure that fingerprint is enabled by unlocking the phone using the PIN, in case if iOS has disabled it due to multiple invalid attempts.
