### ISSUE TITLE
error when build with androidX version

### ISSUE THREAD

**Issue by huyvm** [hieuvp/react-native-fingerprint-scanner#85] opened 2019-05-29 08:13 UTC

**Comment by phillbaker** [comment] 2019-05-29 11:07
Can you provide a stack trace? What version of the library are you using?

**Comment by phillbaker** [comment] 2019-05-30 00:32
Closing as a dupe of https://github.com/hieuvp/react-native-fingerprint-scanner/issues/86 - there's more information there.

**Closed** 2019-05-30 00:32 UTC

**Comment by praveens96** [comment] 2019-06-24 13:17
gettting below error:

> Task :app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform artifact 'fingerprintidentify.aar (com.wei.android.lib:fingerprintidentify:1.2.1)' to match attributes {artifactType=android-manifest}.
      > Execution failed for JetifyTransform: C:\xxx\.gradle\caches\modules-2\files-2.1\com.wei.android.lib\fingerprintidentify\1.2.1\4d29dc54b0145ba76535b98cea61a4dc4a714fc4\fingerprintidentify-1.2.1.aar.
         > Failed to transform 'C:\xxx\.gradle\caches\modules-2\files-2.1\com.wei.android.lib\fingerprintidentify\1.2.1\4d29dc54b0145ba76535b98cea61a4dc4a714fc4\fingerprintidentify-1.2.1.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)

**Comment by codevoler** [comment] 2019-11-05 04:33
- add:
android.useAndroidX=true
android.enableJetifier=true
- use package version: 3.0.0 ("react-native-fingerprint-scanner": "3.0.0")
- migrate to androidx
DONE
