### ISSUE TITLE
Enrollment Fingerprint Changed

### ISSUE THREAD

**Issue by SaruwatariSagittario** [hieuvp/react-native-fingerprint-scanner#47] opened 2018-07-05 08:53 UTC
hi, anyone have a way to listen when the enrolled fingerprint is added or removed ?

**Comment by phillbaker** [comment] 2018-09-07 14:38
Hi @SaruwatariSagittario, I've recently been added as a collaborator on this repo. Can you give an example workflow to help illustrate the problem you're trying to solve?

**Comment by phillbaker** [comment] 2019-07-07 20:25
I believe this is a dupe of #66, going to close as there hasn't been any follow up.

**Closed by phillbaker** 2019-07-07 20:25 UTC
