### ISSUE TITLE
Fatal Exception in Android App

### ISSUE THREAD

**Issue by ANIBIT14** [hieuvp/react-native-fingerprint-scanner#142] opened 2020-06-20 06:37 UTC
Hi, recently we are getting a crash in our Android app a lot because of the fingerprint module.
the stack trace for error is 
Fatal Exception: java.lang.IllegalArgumentException: FragmentActivity must not be null
       at androidx.biometric.BiometricPrompt.<init>(BiometricPrompt.java:61)
       at com.hieuvp.fingerprint.ReactNativeFingerprintScannerModule.getBiometricPrompt(ReactNativeFingerprintScannerModule.java:27)
       at com.hieuvp.fingerprint.ReactNativeFingerprintScannerModule$1.run(ReactNativeFingerprintScannerModule.java:4)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)

It will be great if anyone could provide some insight on it.

**Comment by phillbaker** [comment] 2020-06-20 13:56
Looks like a dupe of https://github.com/hieuvp/react-native-fingerprint-scanner/issues/137, a fix has been merged on master. It was just released as v6.

**Closed** 2020-06-21 05:14 UTC
