### ISSUE TITLE
[Crash] FingerprintPopup makes the app crashes

### ISSUE THREAD

**Issue by to175** [hieuvp/react-native-fingerprint-scanner#40] opened 2018-04-28 19:36 UTC
Hello,
I have last version of react native and my gradle is okay. I did the installation the right way regarding to your guide. I can run my app but once I've added the "example" folder the app creashes... I have removed ios file because I use android only and I have removed "android" in the filename because in the code there is no "android" in the pathname of the import.

I think the crash come from FingerprintPopup  because when I remove this import and this code below, it doesn't crash.

```
const { errorMessage, popupShowed } = this.state;

//...

{errorMessage && (
  <Text style={styles.errorMessage}>
    {errorMessage}
  </Text>
)}

{popupShowed && (
  <FingerprintPopup
    style={styles.popup}
    handlePopupDismissed={this.handleFingerprintDismissed}
  />
)}
```

Why does the app crashes please ? There is no error at all...

Help please :)

**Comment by uniquarkD** [comment] 2018-04-30 04:55
Have you added NSFaceIDUsageDescription on your info.plist?
<key>NSFaceIDUsageDescription</key>
<string>$(PRODUCT_NAME) Authentication</string>

**Comment by to175** [comment] 2018-04-30 11:00
What is the path please ? I don't need iOS yet and I don't  have faceID on my Huawei

**Comment by phillbaker** [comment] 2018-09-25 23:31
Hi all, I've recently been added to this repo as a collaborator and am getting up to speed on the different issues. @to175 can you include a stacktrace of the crash or any other details about the errors that may have caused it?

**Comment by phillbaker** [comment] 2018-11-28 23:04
I'm going to close this issue since there's been no followup. Without specific details of the exception or crash, we can't reproduce or fix the issue. Please re-open if there are further details.

**Closed by phillbaker** 2018-11-28 23:04 UTC

**Comment by NigolBista** [comment] 2020-02-12 23:22
Hello Everyone, 
I followed the installation instruction but the app crashes when i press on the authentication icon.
Whenever `FingerprintScanner.authenticate` is called the app crashes.  

`FingerprintScanner
      .authenticate({ description: this.props.description || 'Log in with Biometrics' })
      .then(() => {
        this.props.onAuthenticate();
      });`

I and doesn't give any errors. 

`React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
      Memory: 4.20 GB / 15.93 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312`

` "react-native-fingerprint-scanner": "^4.0.0",`
` classpath 'com.android.tools.build:gradle:3.4.2'`
`compileSdkVersion = 29
"react": "16.6.3",
 "react-native": "0.58.5",`

I've linked the fingerprint library and also added 
`<uses-permission android:name="android.permission.USE_FINGERPRINT" />
    <uses-permission android:name="android.permission.USE_BIOMETRIC" />` on AndroidManifest.xml
